#!/usr/bin/env python3
"""Sync local Postgres data to remote backend via API using admin credentials.

This script is designed for environments where remote DB access is unavailable,
but admin API access exists.

What it migrates:
- Users (create/update with temp password)
- User profiles (/users/me)
- Ventures (recreated per founder)
- Connections (request + accept replay)
- Messages (replayed sender -> receiver)
- Meetings (recreated by host)

It does NOT directly insert notifications because there is no admin create endpoint.
Notifications are generated by replaying activities above.
"""

from __future__ import annotations

import json
import math
import os
import sys
import time
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

import psycopg2
import requests


LOCAL_DATABASE_URL = os.getenv(
    "LOCAL_DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/uruti_db"
)
REMOTE_BASE_URL = os.getenv("REMOTE_BASE_URL", "http://173.249.25.80:1199")
ADMIN_EMAIL = os.getenv("SYNC_ADMIN_EMAIL", "")
ADMIN_PASSWORD = os.getenv("SYNC_ADMIN_PASSWORD", "")
SYNC_USER_PASSWORD = os.getenv("SYNC_USER_PASSWORD", "UrutiSync@2026")
REQUEST_TIMEOUT = int(os.getenv("SYNC_REQUEST_TIMEOUT", "25"))


@dataclass
class ApiClient:
    base_url: str
    token: Optional[str] = None

    def _headers(self) -> Dict[str, str]:
        headers = {"Content-Type": "application/json"}
        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"
        return headers

    def request(self, method: str, path: str, **kwargs: Any) -> requests.Response:
        url = f"{self.base_url.rstrip('/')}{path}"
        kwargs.setdefault("timeout", REQUEST_TIMEOUT)
        if "headers" not in kwargs:
            kwargs["headers"] = self._headers()
        return requests.request(method, url, **kwargs)

    def json(self, method: str, path: str, **kwargs: Any) -> Any:
        r = self.request(method, path, **kwargs)
        if r.status_code >= 400:
            raise RuntimeError(f"{method} {path} failed: {r.status_code} {r.text[:400]}")
        if not r.text.strip():
            return {}
        return r.json()


def must_env() -> None:
    if not ADMIN_EMAIL or not ADMIN_PASSWORD:
        raise SystemExit(
            "SYNC_ADMIN_EMAIL and SYNC_ADMIN_PASSWORD must be set in env before sync."
        )


def login(base_url: str, email: str, password: str) -> str:
    client = ApiClient(base_url)
    data = client.json(
        "POST",
        "/api/v1/auth/login",
        data=json.dumps({"email": email, "password": password}),
    )
    token = data.get("access_token")
    if not token:
        raise RuntimeError("Login succeeded but access_token is missing")
    return token


def query_rows(conn, sql: str) -> List[Dict[str, Any]]:
    with conn.cursor() as cur:
        cur.execute(sql)
        cols = [d[0] for d in cur.description]
        rows = cur.fetchall()
    out = []
    for row in rows:
        item = {}
        for idx, col in enumerate(cols):
            v = row[idx]
            if hasattr(v, "isoformat"):
                v = v.isoformat()
            item[col] = v
        out.append(item)
    return out


def load_local_data(conn) -> Dict[str, List[Dict[str, Any]]]:
    data = {}
    data["users"] = query_rows(
        conn,
        """
        SELECT id, email, full_name, role::text AS role, is_active, bio, avatar_url, cover_image_url,
               phone, location, linkedin_url, twitter_url, website_url, title, company,
               years_of_experience, expertise, industry, preferred_sectors, investment_focus,
               achievements, funding_amount, stage, email_notifications
        FROM users
        ORDER BY id
        """,
    )
    data["ventures"] = query_rows(
        conn,
        """
        SELECT id, founder_id, name, tagline, description, problem_statement, solution,
               stage::text AS stage, industry::text AS industry, target_market, business_model,
               funding_goal, funding_raised, revenue, monthly_burn_rate, team_size, team_info,
               customers, mrr, highlights, competitive_edge, team_background, funding_plans,
               milestones, activities, logo_url, banner_url, pitch_deck_url, demo_video_url,
               is_published, is_seeking_funding
        FROM ventures
        ORDER BY id
        """,
    )
    data["connections"] = query_rows(
        conn,
        "SELECT id, user1_id, user2_id FROM connections ORDER BY id",
    )
    data["messages"] = query_rows(
        conn,
        """
        SELECT id, sender_id, receiver_id, subject, body, attachments
        FROM messages
        ORDER BY id
        """,
    )
    data["meetings"] = query_rows(
        conn,
        """
        SELECT id, host_id, participant_id, title, description, meeting_type,
               start_time, end_time, timezone, meeting_url, location
        FROM meetings
        ORDER BY id
        """,
    )
    return data


def ensure_remote_users(admin: ApiClient, local_users: List[Dict[str, Any]]) -> Dict[int, Dict[str, Any]]:
    remote_users = admin.json("GET", "/api/v1/users/?skip=0&limit=5000")
    by_email = {u.get("email", "").lower(): u for u in remote_users}
    user_map: Dict[int, Dict[str, Any]] = {}

    for lu in local_users:
        email = (lu.get("email") or "").lower()
        role = str(lu.get("role") or "founder").lower()
        is_sync_admin = email == ADMIN_EMAIL.lower()
        if not email:
            continue

        remote = by_email.get(email)
        if not remote:
            payload = {
                "email": lu["email"],
                "full_name": lu.get("full_name") or lu["email"],
                "role": role,
                "password": SYNC_USER_PASSWORD,
            }
            remote = admin.json("POST", "/api/v1/users/", data=json.dumps(payload))
            by_email[email] = remote
        else:
            update = {
                "email": lu["email"],
                "full_name": lu.get("full_name") or remote.get("full_name") or lu["email"],
                "role": role,
                "is_active": bool(lu.get("is_active", True)),
            }
            if not is_sync_admin:
                update["password"] = SYNC_USER_PASSWORD
            remote = admin.json("PUT", f"/api/v1/users/{remote['id']}", data=json.dumps(update))
            by_email[email] = remote

        user_map[int(lu["id"])] = remote

    return user_map


def login_synced_users(local_users: List[Dict[str, Any]], user_map: Dict[int, Dict[str, Any]]) -> Dict[int, ApiClient]:
    clients: Dict[int, ApiClient] = {}
    for lu in local_users:
        local_id = int(lu["id"])
        remote = user_map.get(local_id)
        if not remote:
            continue

        token = login(REMOTE_BASE_URL, lu["email"], SYNC_USER_PASSWORD)
        c = ApiClient(REMOTE_BASE_URL, token)

        profile_payload = {
            "full_name": lu.get("full_name"),
            "bio": lu.get("bio"),
            "avatar_url": lu.get("avatar_url"),
            "cover_image_url": lu.get("cover_image_url"),
            "phone": lu.get("phone"),
            "location": lu.get("location"),
            "linkedin_url": lu.get("linkedin_url"),
            "twitter_url": lu.get("twitter_url"),
            "website_url": lu.get("website_url"),
            "title": lu.get("title"),
            "company": lu.get("company"),
            "years_of_experience": lu.get("years_of_experience"),
            "expertise": lu.get("expertise"),
            "industry": lu.get("industry"),
            "preferred_sectors": lu.get("preferred_sectors"),
            "investment_focus": lu.get("investment_focus"),
            "achievements": lu.get("achievements"),
            "funding_amount": lu.get("funding_amount"),
            "stage": lu.get("stage"),
            "email_notifications": lu.get("email_notifications"),
        }
        cleaned = {k: v for k, v in profile_payload.items() if v is not None}
        if cleaned:
            c.json("PUT", "/api/v1/users/me", data=json.dumps(cleaned))

        clients[local_id] = c

    return clients


def normalize_venture_payload(v: Dict[str, Any]) -> Dict[str, Any]:
    stage = str(v.get("stage") or "ideation").lower()
    industry = str(v.get("industry") or "other").lower()
    payload = {
        "name": v.get("name"),
        "tagline": v.get("tagline"),
        "description": v.get("description"),
        "problem_statement": v.get("problem_statement"),
        "solution": v.get("solution"),
        "stage": stage,
        "industry": industry,
        "target_market": v.get("target_market"),
        "business_model": v.get("business_model"),
        "funding_goal": v.get("funding_goal"),
        "funding_raised": v.get("funding_raised"),
        "revenue": v.get("revenue"),
        "monthly_burn_rate": v.get("monthly_burn_rate"),
        "team_size": v.get("team_size") or 1,
        "team_info": v.get("team_info"),
        "customers": v.get("customers") or 0,
        "mrr": v.get("mrr"),
        "logo_url": v.get("logo_url"),
    }
    cleaned: Dict[str, Any] = {}
    for key, val in payload.items():
        if val is None:
            continue
        if isinstance(val, float) and (math.isnan(val) or math.isinf(val)):
            continue
        cleaned[key] = val
    return cleaned


def sync_ventures(local_ventures: List[Dict[str, Any]], user_clients: Dict[int, ApiClient]) -> Dict[int, int]:
    venture_map: Dict[int, int] = {}

    ventures_by_founder: Dict[int, List[Dict[str, Any]]] = {}
    for v in local_ventures:
        ventures_by_founder.setdefault(int(v["founder_id"]), []).append(v)

    for founder_id, founder_ventures in ventures_by_founder.items():
        client = user_clients.get(founder_id)
        if not client:
            continue
        remote_existing = client.json("GET", "/api/v1/ventures/my-ventures?skip=0&limit=1000")
        existing_by_name = {rv.get("name", "").strip().lower(): rv for rv in remote_existing}

        for lv in founder_ventures:
            key = (lv.get("name") or "").strip().lower()
            if not key:
                continue
            remote = existing_by_name.get(key)
            if not remote:
                payload = normalize_venture_payload(lv)
                try:
                    remote = client.json("POST", "/api/v1/ventures/", data=json.dumps(payload))
                except Exception as exc:
                    fallback_payload = {
                        "name": lv.get("name"),
                        "description": lv.get("description") or lv.get("tagline") or "Imported venture",
                        "industry": str(lv.get("industry") or "other").lower(),
                        "stage": str(lv.get("stage") or "ideation").lower(),
                    }
                    try:
                        remote = client.json(
                            "POST",
                            "/api/v1/ventures/",
                            data=json.dumps(fallback_payload),
                        )
                        print(
                            f"WARN: venture imported with fallback payload for founder={founder_id} "
                            f"name={lv.get('name')!r}"
                        )
                    except Exception as fallback_exc:
                        print(
                            f"WARN: venture sync failed for founder={founder_id} "
                            f"name={lv.get('name')!r}: {fallback_exc}"
                        )
                        continue
                existing_by_name[key] = remote
            venture_map[int(lv["id"])] = int(remote["id"])

    return venture_map


def sync_connections(local_connections: List[Dict[str, Any]], user_clients: Dict[int, ApiClient], user_map: Dict[int, Dict[str, Any]]) -> int:
    count = 0
    for conn in local_connections:
        u1 = int(conn["user1_id"])
        u2 = int(conn["user2_id"])
        c1 = user_clients.get(u1)
        c2 = user_clients.get(u2)
        r2 = user_map.get(u2)
        if not c1 or not c2 or not r2:
            continue

        try:
            req = c1.json(
                "POST",
                "/api/v1/connections/request",
                data=json.dumps({"user_id": int(r2["id"])}),
            )
            req_id = int(req["id"])
            c2.json("PUT", f"/api/v1/connections/request/{req_id}/accept")
            count += 1
        except Exception:
            continue

    return count


def sync_messages(local_messages: List[Dict[str, Any]], user_clients: Dict[int, ApiClient], user_map: Dict[int, Dict[str, Any]]) -> int:
    count = 0
    for msg in local_messages:
        sender_local = int(msg["sender_id"])
        receiver_local = int(msg["receiver_id"])
        sender_client = user_clients.get(sender_local)
        receiver_remote = user_map.get(receiver_local)
        if not sender_client or not receiver_remote:
            continue

        payload = {
            "receiver_id": int(receiver_remote["id"]),
            "subject": msg.get("subject"),
            "body": msg.get("body") or "",
            "attachments": msg.get("attachments"),
        }
        try:
            sender_client.json("POST", "/api/v1/messages/", data=json.dumps(payload))
            count += 1
        except Exception:
            continue
    return count


def sync_meetings(local_meetings: List[Dict[str, Any]], user_clients: Dict[int, ApiClient], user_map: Dict[int, Dict[str, Any]]) -> int:
    count = 0
    for mt in local_meetings:
        host_local = int(mt["host_id"])
        participant_local = int(mt["participant_id"])
        host_client = user_clients.get(host_local)
        participant_remote = user_map.get(participant_local)
        if not host_client or not participant_remote:
            continue

        payload = {
            "participant_id": int(participant_remote["id"]),
            "title": mt.get("title") or "Meeting",
            "description": mt.get("description"),
            "meeting_type": mt.get("meeting_type"),
            "start_time": mt.get("start_time"),
            "end_time": mt.get("end_time"),
            "timezone": mt.get("timezone") or "Africa/Kigali",
            "meeting_url": mt.get("meeting_url"),
            "location": mt.get("location"),
        }
        payload = {k: v for k, v in payload.items() if v is not None}

        try:
            host_client.json("POST", "/api/v1/meetings/", data=json.dumps(payload))
            count += 1
        except Exception:
            continue
    return count


def main() -> None:
    must_env()

    start = time.time()
    print("[1/6] Logging in as remote admin...")
    admin_token = login(REMOTE_BASE_URL, ADMIN_EMAIL, ADMIN_PASSWORD)
    admin = ApiClient(REMOTE_BASE_URL, admin_token)

    print("[2/6] Reading local Postgres data...")
    conn = psycopg2.connect(LOCAL_DATABASE_URL)
    conn.autocommit = True
    try:
        data = load_local_data(conn)
    finally:
        conn.close()

    print("[3/6] Syncing users and profile shells...")
    user_map = ensure_remote_users(admin, data["users"])

    print("[4/6] Logging in synced users and applying profile details...")
    user_clients = login_synced_users(data["users"], user_map)

    print("[5/6] Syncing ventures, connections, messages, meetings...")
    venture_map = sync_ventures(data["ventures"], user_clients)
    connections_synced = sync_connections(data["connections"], user_clients, user_map)
    messages_synced = sync_messages(data["messages"], user_clients, user_map)
    meetings_synced = sync_meetings(data["meetings"], user_clients, user_map)

    elapsed = round(time.time() - start, 2)
    print("[6/6] Sync finished")
    print(
        json.dumps(
            {
                "users_local": len(data["users"]),
                "users_synced": len(user_map),
                "user_clients_ready": len(user_clients),
                "ventures_local": len(data["ventures"]),
                "ventures_synced": len(venture_map),
                "connections_synced": connections_synced,
                "messages_synced": messages_synced,
                "meetings_synced": meetings_synced,
                "duration_seconds": elapsed,
                "remote_base_url": REMOTE_BASE_URL,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}")
        sys.exit(1)
